[package]
name = "ext_modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "modad"
path = "src/modad.rs"

[dependencies]
