const ogbe: [&str; 31] = [
     "Ogbe Oyeku", 
     "Oyeku Ogbe", 
     "Ogbe Iwori", 
     "Iwori Ogbe", 
     "Ogbe Odi", 
     "Odi Ogbe", 
     "Ogbe Irosun", 
     "Irosun Ogbe", 
     "Ogbe Owonrin", 
     "Owonrin Ogbe", 
     "Ogbe Obara", 
     "Obara Ogbe", 
     "Ogbe Okanran", 
     "Okanran Ogbe", 
     "Ogbe Ogunda", 
     "Ogunda Ogbe", 
     "Ogbe Osa", 
     "Osa Ogbe", 
     "Ogbe Ika", 
     "Ika Ogbe", 
     "Ogbe Oturupon", 
     "Oturupon Ogbe", 
     "Ogbe Otura", 
     "Otura Ogbe", 
     "Ogbe Irete", 
     "Irete Ogbe", 
     "Ogbe Ose", 
     "Ose Ogbe", 
     "Ogbe Ofun", 
     "Ofun Ogbe"
];

const oyeku: [&str; 30] = [
    "Oyeku Iwori",
    "Iwori Oyeku",
    "Oyeku Odi",
    "Odi Oyeku",
    "Oyeku Irosun",
    "Irosun Oyeku",
    "Oyeku Owonrin",
    "Owonrin Oyeku",
    "Oyeku Obara",
    "Obara Oyeku",
    "Oyeku Okanran",
    "Okanran Oyeku",
    "Oyeku Ogunda",
    "Ogunda Oyeku",
    "Oyeku Osa",
    "Osa Oyeku",
    "Oyeku Ika",
    "Ika Oyeku",
    "Oyeku Oturupon",
    "Oturupon Oyeku",
    "Oyeku Otura",
    "Otura Oyeku",
    "Oyeku Irete",
    "Irete Oyeku",
    "Oyeku Ose",
    "Ose Oyeku",
    "Oyeku Ofun",
    "Ofun Oyeku"
];

const iwori: [&str; 29];
